#PTZ config file

#One camera per line in this format:
#CamName url boolean-for-axis-reversal

#Example:
#CamName onvif://user:pass@host:port True/False
#CamName onvifs://user:pass@host:port True/False

#Host can be an IPv4 IPv6 address or a DNS hostname. If using an IPv6 address put it in []
#Use onvif:// if your camera uses HTTP and onvifs:// if your camera uses HTTPS





